### ISSUE TITLE
Liste 20160130

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/TvT_UrbanOps.Altis#34]
- [x] Nachricht auch für Blufor, wenn in control
- [x] "overtime" wenn Blufor in control
- [x] vorbereitungszeit von tageszeit abziehen
- [x] Respawn clickt (hintsilent)
- [x] bei Tod nicht Gruppe verlassen
- [x] Welle ist nicht mehr grün, wenn mehr als benötigt
- [x] TFAR spectator forcen
- [x] Sobald Wellentimer auf 0 wird "respawning" angezeigt obwohl noch nicht genug spieler tot sind
- [x] Ausdauer höher
- [x] Blufor LMG hat 30er Magazine
- [x] Blufor LMG hat Pistolenmunition aber keine Pistole
- [x] Opfor MG hat AK Magazine
- [x] MG Munition Opfor Fehler im Text (10 Rnds)
- [x] Blufor Rauchgranaten im Loadout sind anders als im Shop
- [x] Fortifications gehen nur manchmal
- [x] irgendjemand ist beim respawn in die luft geflogen
- [x] Opfor Respawn sollte länger dauern
- [x] winrate tracker zählt teilweise zu viel games
- [x] RPG7 gekauft --> im Dealerinventar
- [x] ~~Timer für Verteidigungszeit~~
- [x] verbieten feindliche Funkgeräte aufzunehmen - LR GEHT NOCH NICHT

LOG:
https://gist.github.com/McDiod/aa64932b5e2fc37ba805b5161484a669

**Comment by MasaruKondera** [comment]
> Welle ist nicht mehr grün, wenn mehr als benötigt

Kleiner Nachtrag:

Wenn ein Spieler stirbt geht wie immer zuerst der Spielertimer runter und danach der Wellentimer sofern zuvor noch keiner starb.

Sobald der eigene Timer und der Wellentimer auf 0 ist wird jedoch automatisch "respawning" angezeigt und nach ein paar sekunden verschwindet das "Fensterchen" obwohl noch nicht genug spieler tot sind bei dennen der Spielertimer auf 0 ist.

Denke, dass der Text "Respawning" erst dann erscheinen sollte wenn genug spieler vorhanden sind und man auch wirklich respawnt.

**Comment by AdlerSalbei** [comment]
Ich weiß nicht in wie weit es hilft, aber zum Opforspawn, mit dieser berechnung bekommst du einen Punkt genau 1km gegenüber von Blufor. Wobei die Distanz vom Zentrum des Kampfgebietes berechnet wird.

**Comment by Fusselwurm** [comment]
> bei Tod nicht Gruppe verlassen

@McDiod Mir fiel auf, daß Leichen eine eigene Gruppe bekamen (mit BFT), was doof ist. Das wäre der Fix dazu, nehm ich an? :+1: Andererseits würd das heißen, daß wenn ein Truppführer ausfällt, für diesen Trupp das BFT auch kaputt ist, wenn der weiter in der Gruppe ist. :grimacing:

**Comment by McDiod** [comment]
>Sobald der eigene Timer und der Wellentimer auf 0 ist wird jedoch automatisch "respawning" angezeigt 

Danke, gefixt.

>Ich weiß nicht in wie weit es hilft

Danke, hilft leider nicht 😁.

>Das wäre der Fix dazu, nehm ich an? Andererseits würd das nicht-verlassen auch heißen, daß wenn ein Truppführer ausfällt, für diesen Trupp das BFT auch kaputt ist

Genau. Dass das BFT kaputt geht ist schon in Ordnung finde ich. Ist in BC auch so.
