### ISSUE TITLE
Enhance Feeling of Success

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/TvT_UrbanOps.Altis#50]
In yesterdays feedback we found out the current win condition (dominance of the city) may feel artificial, without time-left indication its hard to justify an "all in" last battle.

To further the feeling of conquering the city I suggest (maybe 3) irreversible actions BLUFOR can take to symbolically bolster their standing in the city. This might be destroying weapon cache, burning a flag, destroying the propaganda speakers, [...] and getting benefits from doing so (extending necessary defense time?).

Accomplishing those could even be an alternative winning condition with one benefit: BLUFOR has to move through most of the city in search for the objectives and cant just stay in one spot, going more or less in defending mode and abusing their manpower, which I fear will become a very viable tactic.

Granted this probably would need even more play time and doesnt solve the initial problem of a sudden ending (if the defending time is over).

**Comment by McDiod** [comment]
Guter Punkt. Die "In-die-Stadt-reinheizen-und-sich-festsetzen" Strategie ist wahrscheinlich sehr stark im Moment aber relativ langweilig. Weitere Winconditions für Blufor würden gegensteuern. Allerdings darf Opfor nicht die Position(en) wissen, damit sie ihre Verteidigung nicht ausschließlich darauf konzentrieren können. Dealer oder Propagandatürme fallen also flach.

* irgendein Objekt an einem bestimmten Punkt aufstellen (Flagge?)
* eine Anzahl an bestimmten Zivilisten (töten?/gefangen nehmen?/aus der Stadt retten?), von denen nur Blufor weiss, wie sie zu erkennen sind

**Comment by McDiod** [comment]
4c975896301a783f40d624fb80aca36089174256

https://github.com/gruppe-adler/TvT_UrbanOps.Altis/wiki/Win-Conditions-BLUFOR

**Comment by nomisum** [comment]
Klingt super.
