### ISSUE TITLE
Wettervorschau auf Karte während Spawnauswahl

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/TvT_UrbanOps.Altis#55]

**Comment by McDiod** [comment]
https://github.com/gruppe-adler/TvT_UrbanOps.Altis/blob/master/functions/choosePlayArea/fn_showWeatherPreview.sqf

Problem:
PIP wird auf Karte nicht gerendert. Wenn Karte geöffnet wird, bevor die Welt das erste mal gerendert wird bleibt die Vorschau schwarz.

**Comment by nomisum** [comment]
voll geile idee!

**Comment by McDiod** [comment]
a4a6407842c8c94fe14316f3964c008704697df7
