### ISSUE TITLE
Respawnende machen pro Person eine Gruppe auf

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/TvT_UrbanOps.Altis#65]

**Comment by McDiod** [comment]
Als Playerhost nicht reproduzierbar.

**Comment by dedmen** [comment]
https://github.com/gruppe-adler/TvT_UrbanOps.Altis/blob/master/description.ext#L32 Das spawned eine neue Einheit ohne Gruppe == Neue gruppe wird erstellt.

**Comment by McDiod** [comment]
fixed
